# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160402_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='age',
            new_name='year',
        ),
    ]
